package darwin

import (
	"os"
	"path/filepath"
)

const (
	LABEL      = "com.builtbyjb.yay"
	PLIST_NAME = LABEL + ".plist"
	AGENT_DIR  = "/Library/LaunchAgents"
)

var PlistTemplate = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Do NOT edit this file manually — it is auto-generated by yay -->
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{{.Label}}</string>

    <key>ProgramArguments</key>
    <array>
        <string>{{.BinaryPath}}</string>
        <string>run</string>
    </array>

    <key>RunAtLoad</key>
    <true/>

    <key>KeepAlive</key>
    <true/>

    <key>LimitLoadToSessionType</key>
    <string>Aqua</string>

    <key>ProcessType</key>
    <string>Interactive</string>

    <key>StandardOutPath</key>
    <string>{{.LogDir}}/yay.out.log</string>

    <key>StandardErrorPath</key>
    <string>{{.LogDir}}/yay.err.log</string>

    <key>WorkingDirectory</key>
    <string>{{.WorkingDir}}</string>
</dict>
</plist>
`

type PlistData struct {
	Label      string
	BinaryPath string
	LogDir     string
	WorkingDir string
}

func PlistPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, AGENT_DIR, PLIST_NAME)
}
